/* auto-generated by NAPI-RS */
/* eslint-disable */

export interface ErrorLabel {
  message: string | null;
  start: number;
  end: number;
}

export interface OxcError {
  severity: Severity;
  message: string;
  labels: Array<ErrorLabel>;
  helpMessage: string | null;
  codeframe: string | null;
}

export declare const enum Severity {
  Error = "Error",
  Warning = "Warning",
  Advice = "Advice",
}

/** A hoisted script extracted from an Astro component. */
export interface NapiHoistedScript {
  /** The script type: `"inline"` or `"external"`. */
  type: string;
  /** The inline script code (when type is `"inline"`). */
  code?: string;
  /** The external script src URL (when type is `"external"`). */
  src?: string;
}

/** A hydrated component reference found in the template. */
export interface NapiHydratedComponent {
  /** The export name from the module (e.g., `"default"`). */
  exportName: string;
  /** The local variable name used in the component. */
  localName: string;
  /** The import specifier (e.g., `"../components/Counter.jsx"`). */
  specifier: string;
  /** The resolved path (empty string if unresolved). */
  resolvedPath: string;
}

/** Result of compiling an Astro file. */
export declare class AstroCompileResult {
  /** The generated JavaScript code. */
  get code(): string;
  /** Source map JSON string (empty until sourcemap support is implemented). */
  get map(): string;
  /** CSS scope hash for the component. */
  get scope(): string;
  /** Extracted CSS from `<style>` tags (empty until CSS support). */
  get css(): string[];
  /** Hoisted scripts extracted from the template. */
  get scripts(): NapiHoistedScript[];
  /** Components with `client:*` hydration directives (except `client:only`). */
  get hydratedComponents(): NapiHydratedComponent[];
  /** Components with `client:only` directive. */
  get clientOnlyComponents(): NapiHydratedComponent[];
  /** Server components (stub: always empty). */
  get serverComponents(): NapiHydratedComponent[];
  /** Whether the template contains an explicit `<head>` element. */
  get containsHead(): boolean;
  /** Whether the component propagates head content. */
  get propagation(): boolean;
  /** Style processing errors (stub: always empty). */
  get styleError(): string[];
  /** Diagnostic messages (stub: always empty). */
  get diagnostics(): string[];
  /** Any compilation errors encountered (oxc-specific). */
  get errors(): Array<OxcError>;
}

/**
 * Options for compiling Astro files to JavaScript.
 *
 * Matches the Go compiler's `TransformOptions` from `@astrojs/compiler`.
 * Fields marked as stubs are accepted for API compatibility but not yet functional.
 */
export interface AstroCompileOptions {
  /**
   * The filename of the Astro component being compiled.
   * Used in the `$$createComponent` call for debugging.
   */
  filename?: string;
  /**
   * A normalized version of the filename used for scope hash generation.
   * If not provided, falls back to `filename`.
   */
  normalizedFilename?: string;
  /**
   * The import specifier for Astro runtime functions.
   * Defaults to `"astro/runtime/server/index.js"`.
   */
  internalUrl?: string;
  /**
   * Whether to generate a source map.
   * **Stub**: not yet implemented.
   *
   * @default false
   */
  sourcemap?: boolean;
  /**
   * Arguments passed to `$$createAstro` when the Astro global is used.
   * Defaults to `"https://astro.build"`.
   */
  astroGlobalArgs?: string;
  /**
   * Whether to collapse whitespace in the HTML output.
   * **Stub**: not yet implemented.
   *
   * @default false
   */
  compact?: boolean;
  /**
   * Enable scoped slot result handling.
   * **Stub**: not yet implemented.
   *
   * @default false
   */
  resultScopedSlot?: boolean;
  /**
   * Strategy for CSS scoping: `"where"`, `"class"`, or `"attribute"`.
   * **Stub**: not yet implemented.
   *
   * @default "where"
   */
  scopedStyleStrategy?: "where" | "class" | "attribute";
  /**
   * URL for the view transitions animation CSS.
   * **Stub**: not yet implemented.
   */
  transitionsAnimationUrl?: string;
  /**
   * Whether to annotate generated code with the source file path.
   * **Stub**: not yet implemented.
   *
   * @default false
   */
  annotateSourceFile?: boolean;
  /**
   * Whether to render processed script tags using `$$renderScript`.
   *
   * @default false
   */
  renderScript?: boolean;
  /**
   * Enable experimental script ordering behavior.
   * **Stub**: not yet implemented.
   *
   * @default false
   */
  experimentalScriptOrder?: boolean;
  /**
   * Whether to include the `$$metadata` export.
   * The Go compiler always includes metadata; this option lets you skip it.
   * (oxc-specific)
   *
   * @default false
   */
  includeMetadata?: boolean;
  /**
   * Whether to strip HTML comments from component slot children.
   * Matches the official Astro compiler behavior by default.
   * (oxc-specific)
   *
   * @default true
   */
  stripSlotComments?: boolean;
}

/**
 * Compile Astro file to JavaScript asynchronously on a separate thread.
 *
 * This transforms an Astro file into JavaScript code compatible with the Astro runtime.
 * The output follows the same format as the official Astro compiler.
 *
 * Generally `compileAstroSync` is preferable to use as it does not have the overhead
 * of spawning a thread. If you need to parallelize compilation of multiple files,
 * it is recommended to use worker threads.
 *
 * @example
 * ```javascript
 * import { compileAstro } from 'oxc-astro';
 *
 * const result = await compileAstro(`---
 * const name = "World";
 * ---
 * <h1>Hello {name}!</h1>`, {
 *   filename: 'Component.astro',
 *   includeMetadata: true,
 * });
 *
 * console.log(result.code); // Generated JavaScript
 * ```
 */
export declare function compileAstro(
  sourceText: string,
  options?: AstroCompileOptions | undefined | null,
): Promise<AstroCompileResult>;

/**
 * Compile Astro file to JavaScript synchronously on current thread.
 *
 * This transforms an Astro file into JavaScript code compatible with the Astro runtime.
 * The output follows the same format as the official Astro compiler.
 *
 * @example
 * ```javascript
 * import { compileAstroSync } from 'oxc-astro';
 *
 * const result = compileAstroSync(`---
 * const name = "World";
 * ---
 * <h1>Hello {name}!</h1>`, {
 *   filename: 'Component.astro',
 *   includeMetadata: true,
 * });
 *
 * console.log(result.code); // Generated JavaScript
 * ```
 */
export declare function compileAstroSync(
  sourceText: string,
  options?: AstroCompileOptions | undefined | null,
): AstroCompileResult;
