/* auto-generated by NAPI-RS */
/* eslint-disable */

export interface ErrorLabel {
  message: string | null
  start: number
  end: number
}

export interface OxcError {
  severity: Severity
  message: string
  labels: Array<ErrorLabel>
  helpMessage: string | null
  codeframe: string | null
}

export declare const enum Severity {
  Error = 'Error',
  Warning = 'Warning',
  Advice = 'Advice'
}

/** Result of compiling an Astro file. */
export declare class AstroCompileResult {
  /** The generated JavaScript code. */
  get code(): string
  /** Any compilation errors encountered. */
  get errors(): Array<OxcError>
}

/** Options for compiling Astro files to JavaScript. */
export interface AstroCompileOptions {
  /**
   * The import specifier for Astro runtime functions.
   * Defaults to `"astro/runtime/server/index.js"`.
   */
  internalUrl?: string
  /**
   * The filename of the Astro component being compiled.
   * Used in the `$$createComponent` call for debugging.
   */
  filename?: string
  /**
   * Whether to include the `$$metadata` export.
   * This is used for hydration and module tracking.
   *
   * @default false
   */
  includeMetadata?: boolean
  /**
   * Arguments passed to `$$createAstro` when the Astro global is used.
   * Defaults to `"https://astro.build"`.
   */
  astroGlobalArgs?: string
  /**
   * Whether to strip HTML comments from component slot children.
   * Matches the official Astro compiler behavior by default.
   *
   * @default true
   */
  stripSlotComments?: boolean
}

/**
 * Compile Astro file to JavaScript asynchronously on a separate thread.
 *
 * This transforms an Astro file into JavaScript code compatible with the Astro runtime.
 * The output follows the same format as the official Astro compiler.
 *
 * Generally `compileAstroSync` is preferable to use as it does not have the overhead
 * of spawning a thread. If you need to parallelize compilation of multiple files,
 * it is recommended to use worker threads.
 *
 * @example
 * ```javascript
 * import { compileAstro } from 'oxc-astro';
 *
 * const result = await compileAstro(`---
 * const name = "World";
 * ---
 * <h1>Hello {name}!</h1>`, {
 *   filename: 'Component.astro',
 *   includeMetadata: true,
 * });
 *
 * console.log(result.code); // Generated JavaScript
 * ```
 */
export declare function compileAstro(sourceText: string, options?: AstroCompileOptions | undefined | null): Promise<AstroCompileResult>

/**
 * Compile Astro file to JavaScript synchronously on current thread.
 *
 * This transforms an Astro file into JavaScript code compatible with the Astro runtime.
 * The output follows the same format as the official Astro compiler.
 *
 * @example
 * ```javascript
 * import { compileAstroSync } from 'oxc-astro';
 *
 * const result = compileAstroSync(`---
 * const name = "World";
 * ---
 * <h1>Hello {name}!</h1>`, {
 *   filename: 'Component.astro',
 *   includeMetadata: true,
 * });
 *
 * console.log(result.code); // Generated JavaScript
 * ```
 */
export declare function compileAstroSync(sourceText: string, options?: AstroCompileOptions | undefined | null): AstroCompileResult
